config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy
  resources :movies, only: :index
end


        #           Prefix Verb   URI Pattern                                                                              Controller#Action
        #    list_bookmarks POST   /lists/:list_id/bookmarks(.:format)                                                      bookmarks#create
        # new_list_bookmark GET    /lists/:list_id/bookmarks/new(.:format)                                                  bookmarks#new                                                    movies#show
        #             lists GET    /lists(.:format)                                                                         lists#index
        #                   POST   /lists(.:format)                                                                         lists#create
        #          new_list GET    /lists/new(.:format)                                                                     lists#new
        #              list GET    /lists/:id(.:format)                                                                     lists#show
        #          bookmark DELETE /bookmarks/:id(.:format)                                                                 bookmarks#destroy
        #            movies GET    /movies(.:format)                                                                        movies#index

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
	has_many :bookmarks, dependent: :destroy
	has_many :movies, through: :bookmarks
	validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :bookmarks
	validates :title, presence: true, uniqueness: true
	validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @bookmark.list = @list
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list, notice: 'Your movie is added.'
    else
      render :new
    end
  end

  def destroy
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmark.list = @list


  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @lists = List.all
    if @list.save
      redirect_to lists_path, notice: 'Your List is created.'
    else
      render :index
    end
  end

  private
  def list_params
    params.require(:list).permit(:name, :image_url)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all
	end

	def show
		@movie = Movie.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>
<div>
	<%= simple_form_for [@list, @bookmark] do |f| -%>
		<%= f.error_notification %>
	  	<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
		<%= f.association :movie %>
		<%= f.input :comment %>
		<%= f.submit "Add Movie", class: "btn btn-primary" %>
	<% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark justify-content-between">
      <a class="navbar-brand" href="/movies"><span class="text-brand">Kisooooz</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/movies"><span class="text-yellow">Home</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/lists"><span class="text-yellow">!Like</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="bg-light py-2 px-4">
	<%= simple_form_for @list do |f| -%>
	<%= f.error_notification %>
  	<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
	<%= f.input :name %>
	<%= f.input :image_url %>
	<%= f.submit "Add List", class: "btn btn-success" %>
	<% end -%>
</div>

app/views/lists/index.html.erb
<div class="headers">
	<h1>Make Your List</h1>
	<a class="btn btn btn-outline-success" href="#addForm">Add List</a>
</div>



<div class="listcard">
	<div class="container-fluid contenedor text-center">
	   <div class=" container text-center d-flex flex-row flex-wrap bd-highlight mb-3">
	   	<% @lists.each do |list| %>	
	      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 container_foto ">
	         <div class="ver_mas text-center">
	            <span id="eye">
		            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
	  				<path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
	 				<path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
					</svg>
				</span>
	         </div>
	         <article class="text-left">
	            <h2 id="listname"><%= link_to list.name, list_path(list) %></h2>
	         </article>
	        <%= image_tag list.image_url %>
	      </div>
	    <% end -%>
	   </div>
	</div>
</div>


<section class="container-form" id="addForm">
  <div class="card-form">
    <div class="content">
      <h6> Add List</h6>
      <div class="hover_content">
        <p>
			<div>
				<%= render "form"%>
			</div>
        </p>
      </div>
    </div>
  </div>       
</section>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=  @list.image_url %>);">
  <div class="container">
    <h1>My <%= @list.name.capitalize %> Movie Box</h1>
    <a class="btn btn btn-outline-success mt-5" href="#addForm">Add Movie</a>
  </div>
</div>




<body>
  <div class="py-5">
    <div class="container">
      <div class="row hidden-md-up">
		  <% @list.bookmarks.each do |bookmark| %>
		  <div class="card w-50">
      		<div class="card-block">
			    <%= image_tag bookmark.movie.poster_url, alt: "movie poster", class: "col-md-4 col-xl-3" %>
			    <%= bookmark.movie.title %>
			    <br>
			    <p>comment: <%= bookmark.comment %></p> 
      		</div>
		  </div>
		  <% end %>
        </div>
      </div>
    </div>
  </div>
</body>



<section class="container-form" id="addForm">
  <div class="card-form">
    <div class="content">
      <!-- <img class="logo" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/76882/logo.svg" alt="mparticle"> -->
      <h6> Add Movie</h6>
      <div class="hover_content">
        <p>
			<div>
				<%= simple_form_for [@list, @bookmark] do |f| -%>
				<%= f.error_notification %>
			  	<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
				<%= f.association :movie %>
				<%= f.input :comment %>
				<%= f.submit "Add Movie", class: "btn btn-primary" %>
				<% end -%>
			</div>
        </p>
      </div>
    </div>
  </div>       
</section>

app/views/movies/index.html.erb
<!-- 	<div>
		<span >Rotten Apples</span>
		<h1>Hi Stranger!</h1>
		<p>
			 "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti."
			 <br>
			 The Silence of the Lambs (1991)
		</p>
	</div>
 -->

<div class="big_container px-5">
	    <div class="row">
	    	<% @movies.each do |movie| %>
		        <div class="col-sm-6 col-md-3">
		            <div class="profile-card">
		                <div class="profile-img">
		                    <%= image_tag movie.poster_url, alt: "movie posters" %>
		                </div>
		                <div class="profile-content">
		                    <h2 class="title"><%= movie.title %>
		                        <span>Rating | <%= movie.rating %></span>
		                        <span id="overview"><%= movie.overview %></span>
		                    </h2>
		                    <ul class="social-link">
		                        <li><a href="/lists"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-heart" viewBox="0 0 16 16">
		                        <path fill-rule="evenodd" d="M8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"/>
		                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/></svg></a></li>
		                    </ul>
		                </div>
		            </div>
		        </div>
	        <% end -%>
	    </div>
</div>